tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views
from rango.views import UserListView, PageListView, AddCategoryView, AddPageView, IndexView, RegisterProfileView, EditProfileView

app_name = 'rango'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('about/', views.about, name='about'),
    path('category/<str:category_name_slug>/', PageListView.as_view(), name='show_category'),
    path('add_category/', AddCategoryView.as_view(), name='add_category'),
    path('goto/', views.track_url, name='goto'),
    path('category/<str:category_name_slug>/add_page/', AddPageView.as_view(), name='add_page'),
    path('logout/', views.user_logout, name='logout'),
    path('add_profile/', RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<slug:user_slug>', EditProfileView.as_view(), name='profile'),
    path('users/', UserListView.as_view(), name='users'),
    path('like/', views.like_category, name='like_category'),
    path('suggest/', views.suggest_category, name='suggest_category')
]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.urls import reverse
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from rango.views import IndexView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    max_name_length = 128

    name = models.CharField(max_length=max_name_length, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        if self.views < 0:
            self.views = 0
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('rango:show_category', 
                        kwargs={'category_name_slug': self.slug})

class Page(models.Model):
    max_title_length = 128

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=max_title_length)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('rango:show_category', 
                        kwargs={'category_name_slug': self.category.slug})

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_slug = models.SlugField(unique=True)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def save(self, *args, **kwargs):
        self.user_slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('rango:profile', kwargs={'user_slug': self.user_slug})

tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from datetime import datetime
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView

# Import the Category and Page models
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User

""" # A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):

    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        # update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        # set the last visit cookie
        request.session['last_visit'] = last_visit_cookie
    
    # Update/set the visits cookie
    request.session['visits'] = visits


def index(request):
    # Query the database for a list of ALL categories currently stored.
    # Order the categories by no. likes in descending order.
    # Retrieve the top 5 only - or all if less than 5.
    # Place the list in our context_dict dictionary
    # that will be passed to the template engine.

    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    # Obtain our Response object early so we can add cookie information.
    response =  render(request, 'rango/index.html', context=context_dict)

    #Call function to handle the cookies
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    # Return response back to the user, updating any cookies that need change.
    return response """

class IndexView(ListView):
    template_name = 'rango/index.html'
    context_object_name = 'pages'
    queryset = Page.objects.order_by('-views')[:5] 

    def get_context_data(self):
        context = super().get_context_data()
        context['categories'] = Category.objects.order_by('-likes')[:5]
        return context

def about(request):
    context_dict = {}
    #visitor_cookie_handler(request)
    #context_dict['visits'] = request.session['visits']
    return render(request, 'rango/about.html', context_dict)

class PageListView(ListView):
    template_name = "rango/category.html"
    context_object_name = "pages"

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['category_name_slug'])
        return Page.objects.filter(category=self.category).order_by('-views')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context

def track_url(request):
    page_id = None
    url = 'rango/index/'

    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']

            try:
                page = Page.objects.get(id=page_id)
                page.views += 1
                page.save()
                url = page.url
            except:
                pass
                
    return redirect(url)

class AddCategoryView(CreateView):
    template_name = 'rango/add_category.html'
    model = Category
    fields = ['name']

class AddPageView(CreateView):
    template_name = 'rango/add_page.html'
    model = Page
    fields = ['title', 'url']

    def form_valid(self, form, **kwargs):
        form.instance.category = get_object_or_404(Category, slug=self.kwargs['category_name_slug'])
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category, slug=self.kwargs['category_name_slug'])
        return context

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@method_decorator(login_required, name='dispatch')
class RegisterProfileView(CreateView):
    template_name = 'rango/profile_registration.html'
    model = UserProfile
    fields = ['website', 'picture']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class EditProfileView(UpdateView):
    template_name = 'rango/profile.html'
    model = UserProfile
    fields = ['website', 'picture']
    slug_field = 'user_slug'
    slug_url_kwarg = 'user_slug'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        user = User.objects.get(username=self.kwargs['user_slug'])
        user_profile = UserProfile.objects.get(user=user)
        context = super().get_context_data(**kwargs)
        context['user_profile'] = user_profile
        context['selected_user'] = user
        return context

@method_decorator(login_required, name='dispatch')
class UserListView(ListView):
    model = UserProfile
    template_name = 'rango/users.html'
    context_object_name = 'user_profiles'

@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()
    return HttpResponse(likes)

def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)

    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]
    return cat_list

def suggest_category(request):
    cat_list = []
    starts_with = ''

    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(8, starts_with)

    if len(cat_list) == 0:
            cat_list = Category.objects.order_by('-likes')

    return render(request, 'rango/cats.html', {'cats': cat_list })

tango_with_django_project/rango/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <head>
        <h1>This tutorial has been put together by Ethan Scruton</h1><br />
    </head>
    
    <p>
        I was able to put this website together with the help of the book <a href='https://www.tangowithdjango.com/'>Tango With Django.</a>
    </p>
    <p>
        The site allows users to add and like categories. Within each category, users can add and view webpages.
    </p>
{% endblock %}

tango_with_django_project/rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Add Category
{% endblock %}

{% block body_block %}
    {% if user.is_authenticated %}
        <form role="form" id="category_form" method="post" 
            action="{% url 'rango:add_category' %}">
            <h2 class="form-signin-heading"> Add a Category </h2>
            {% csrf_token %}
            {{ form.as_p }}
            <br/>
            <button class="btn btn-primary" type="submit" name="submit">
                Add Category
            </button>
        </form>
    {% else %}
        <h1>Must be logged in to add a category.</h1>
    {% endif %}
{% endblock %}

tango_with_django_project/rango/templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Add Page
{% endblock %}

{% block body_block %}
    {{ ctx }}
    {% if user.is_authenticated %}
        {% if category %}
            <form role="form" id="page_form" method="post" 
                action="{% url 'rango:add_page' category.slug %}">
                <h2 class="form-signin-heading"> Add a Page to
                    <a href="{% url 'rango:show_category' category.slug %}">
                        {{ category.name }}
                    </a>
                </h2>
                {% csrf_token %}
                {{ form.as_p }}
                <br/>
                <button class="btn btn-primary" type="submit" name="submit">
                    Add Page
                </button>
            </form>
        {% else %}
            <p>This category does not exist.</p>
        {% endif %}
    {% else %}
        <p>Must be logged in to add a page.</p>
    {% endif %}
{% endblock %}

tango_with_django_project/rango/templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,
                                        initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{% static 'images/favicon.ico' %}">
        <title>
            Rango - {% block title %}How to Tango with Django!{% endblock %}
        </title>
        <!-- Bootstrap core CSS -->
        <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"
            rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href=
            "http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
            rel="stylesheet">
    </head>

    <body>
        <nav class="navbar fixed-top navbar-toggleable-sm navbar-inverse bg-inverse">
            <a class="navbar-brand" href="#">Rango</a>

            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:index' %}">Index</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:about' %}">About</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/index/">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'rango:users' %}?next=/rango/index/">Profiles</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <input class="input-medium search-query" type="search" id="search-input" placeholder="Search..."/>
                    <div id="categories-listing">
                        {% block sidebar_block %}
                            {% get_category_list category %}
                        {% endblock %}
                    </div>
                </div>
                <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3 main">
                    {% block body_block %}{% endblock %}
                </div>
            </div>
        </div>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-ajax.js' %}"></script>
        <script
        src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
        </script> 
    </body>
</html>

tango_with_django_project/rango/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>

        <div>
            <strong id="like_count">{{ category.likes }}</strong> people like this category
            {% if user.is_authenticated %}
                <button id="likes" data-catid="{{ category.id }}"
                    class="btn btn-primary btn-small" type="button">
                    Like
                </button>
            {% endif %}
        </div>

        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                            ({{ page.views }} view{% if page.views != 1 %}s{% endif %})
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
        {% endif %}
    {% else %}
            The specified category does not exist!
    {% endif %}
{% endblock %}

tango_with_django_project/rango/templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li>
                <strong>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </strong>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

tango_with_django_project/rango/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}

    <div class="jumbotron">
        <h1 class="display-3">Rango says...</h1>
        {% if user.is_authenticated %}
            <h1>hey there {{ user.username }}!</h1>
        {% else %}
            <h1>hey there partner!</h1>
        {% endif %} 
    </div>

    <div class="row marketing">
        <div class="col-lg-6">
            <h4>Most Liked Categories</h4>
            <p>
                {% if categories %}
                <ul class="list-group">
                    {% for category in categories %}
                        <li class="list-group-item">
                            <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
                {% else %}
                    <strong>There are no categories present.</strong>
                {% endif %}
            </p>
        </div>

        <div class="col-lg-6">
            <h4>Most Viewed Pages</h4>
            <p>
                {% if pages %}
                <ul class="list-group">
                    {% for page in pages %}
                        <li class="list-group-item">
                            <a href="{{ page.url }}">{{ page.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
                {% else %}
                    <strong>There are no pages present.</strong>
                {% endif %}
            </p>
        </div>
    </div>

    <img src="{% static "images/dwight.jpeg" %}"
            alt="Picture of Dwight" />
{% endblock %}

tango_with_django_project/rango/templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {{ selected_user.username }} Profile
{% endblock %}

{% block body_block %}
    <h1>{{ selected_user.username}} Profile</h1>
    {% if user_profile.picture %}
        <img src="{{ MEDIA_URL }}{{ user_profile.picture }}"
            width="300"
            height="300"
            alt="{{ selected_user.username }}" />
    {% else %}
        <img src="http://www.lorempixel.com/300/300/people/"
            width="300"
            height="300"
            alt="{{ selected_user.username }}" />
    {% endif %}
    <br/>
    <div>
        {% if selected_user.username == user.username %}
            <form method="post" action="{{ user.username }}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Update" />
            </form>
        {% else %}
            <p><strong>Website: </strong><a href="{{ user_profile.website }}">
                {{ user_profile.website }}</a></p>
        {% endif %}
    </div>
{% endblock %}

tango_with_django_project/rango/templates/rango/profile_registration.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Register Profile
{% endblock %}

{% block body_block %}
    <form role="form" method="post" action="." enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        </br>
        <button class="btn btn-primary" name="submit" type="submit">
            Register Profile
        </button>
    </form>
{% endblock %}

tango_with_django_project/rango/templates/rango/users.html
{% extends 'rango/base.html' %}

{% block title_block %}
    List Of User Profiles
{% endblock %}

{% block body_block %}
    <h1>User Profiles</h1>
    <div class="panel">
        {% if user_profiles %}
        <div class="panel-body">
            <div class="list-group">
                {% for user_profile in user_profiles %}
                    <div class = "list-group-item">
                        <div class="image-parent">
                            {% if user_profile.picture %}
                                <img src="{{ MEDIA_URL }}{{ user_profile.picture }}"
                                    width="64"
                                    height="64"
                                    alt="{{ user_profile.username }}" />
                            {% else %}
                                <img src="http://www.lorempixel.com/64/64/people/"
                                    width="64"
                                    height="64"
                                    alt="{{ user_profile.username }}" />
                            {% endif %}
                        </div>
                        <h4 class="list-group-item-heading">
                            <a href="{% url 'rango:profile' user_profile.user_slug %}">
                                {{ user_profile.user.username }}
                            </a>
                        </h4>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% else %}
            <p>There are no users for this site.</p>
        {% endif %}
    </div>

{% endblock %}